# Generated by Django 5.2.7 on 2025-10-14 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('port', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=20)),
                ('min_distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(default='Offline', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Normal', 'Normal'), ('Falla', 'Falla')], default='Normal', max_length=10)),
                ('power', models.CharField(choices=[('POWER-ON', 'POWER-ON'), ('POWER-OFF', 'POWER-OFF')], default='POWER-ON', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ONT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ont_id', models.PositiveIntegerField()),
                ('service_port', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('sn', models.CharField(max_length=100)),
                ('control_flag', models.CharField(default='active', max_length=50)),
                ('run_state', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=50)),
                ('config_state', models.CharField(blank=True, default='Initial', max_length=50, null=True)),
                ('match_state', models.CharField(choices=[('Match', 'Match'), ('Mismatch', 'Mismatch'), ('Initial', 'Initial')], default='Initial', max_length=50)),
                ('protect_side', models.CharField(blank=True, max_length=50, null=True)),
                ('puerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onts', to='olt.puerto')),
            ],
        ),
        migrations.AddField(
            model_name='puerto',
            name='tarjeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puertos', to='olt.tarjeta'),
        ),
    ]
