# Generated by Django 5.2.7 on 2025-10-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Suspendido', 'Suspendido')], default='Activo', max_length=15)),
                ('nombre', models.CharField(max_length=100)),
                ('dui', models.CharField(max_length=10, unique=True)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
